smqtt:
  logLevel: DEBUG
  tcp:
    port: 1883
    username: smqtt
    password: smqtt
    wiretap: true
    bossThreadSize: 4
    workThreadSize: 8
    lowWaterMark: 4000000
    highWaterMark: 80000000
    ssl:
      enable: false
  http:
    enable: true
    accessLog: true
    ssl:
      enable: false
    admin:
      enable: true
      username: smqtt
      password: smqtt
  ws:
    enable: true
    port: 8999
    path:
  cluster:
    enable: false
    url: 127.0.0.1:7771,127.0.0.1:7772
    port: 7771
    node: node-1
    external:
      host: localhost
      port: 7777
db:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/smqtt?characterEncoding=utf-8&useSSL=false&useInformationSchema=true&serverTimezone=UTC
  username: root
  password: 123
  initialSize: 10
  maxActive: 300
  maxWait: 60000
  minIdle: 2
redis:
  mode: single
  database: 0
  password:
  timeout: 3000
  poolMinIdle: 8
  poolConnTimeout: 3000
  poolSize: 10
  single:
    address: 127.0.0.1:6379
  cluster:
    scanInterval: 1000
    nodes: 127.0.0.1:7000,127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005
    readMode: SLAVE
    retryAttempts: 3
    slaveConnectionPoolSize: 64
    masterConnectionPoolSize: 64
    retryInterval: 1500
  sentinel:
    master: mymaster
    nodes: 127.0.0.1:26379,127.0.0.1:26379,127.0.0.1:26379
